services:
  posevariations:
    build:
      context: .
      dockerfile: Dockerfile
    image: posevariations:latest
    container_name: posevariations
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./outputs:/app/outputs
    restart: unless-stopped
