services:
  AI Image Variations:
    build:
      context: .
      dockerfile: Dockerfile
    image: AI Image Variations:latest
    container_name: AI Image Variations
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./outputs:/app/outputs
    restart: unless-stopped
